export const expectedStudios = [
    'Austin/Lakeway',
    'Birmingham/Homewood',
    'Brentwood/Hill Center',
    'Charlotte/Stonecrest',
    'Chicago Glenview',
    'Chicago Lakeview',
    'Chicago_Libertyville',
    'Dallas/Preston Center (Next to Starbucks)',
    'Downtown Franklin',
    'Edmond Oklahoma',
    'Houston',
    'Little Rock - Chenal',
    'Manduu Collierville',
    'Memphis/Perkins at Poplar',
    'Memphis/Poplar at Kirby',
    'Naples Mercato',
    'Nashville/Green Hills',
    'Kenosha',
    'Migrate Test Studio'
  ];