export const expectedStudios = [
  // 'Memphis/Collierville',
  // 'Charlotte/Stonecrest',
  'Little Rock - Chenal',
  // 'Chicago Glenview',
  // 'Kenosha',
  // 'Chicago Libertyville',
  // 'Dallas/Preston Center',
  'Edmond Oklahoma',
  'Austin/Lakeway',
  // 'Memphis/Poplar at Kirby',
  // 'Nashville/Green Hills',
  'Houston',
  // 'MU Lab',
  'Downtown Franklin',
  'Birmingham/Homewood',
  'Brentwood/Hill Center',
];
